language: node_js
node_js:
- '6'
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm install -g npm@6
deploy:
  provider: npm
  email: kellyselden@gmail.com
  api_key:
    secure: v+NRHXuM/LdN3gL7Eb65mURnfuP06kp9vPsxZzcVZf0Rkp9+ew/dLX0ef0Pr3dML7pAERAY+Z8ex83wGocjmhmY31E6V/vgvAOPNiUC5+kJIYRQkIPIXaB3WPR6ZiEKs5Z/BB3QTWXnCU60m8fYy7zSdcsqbXf6x75+sqRRgUqOaUkugA+2k2RfQXDlQFn2llFWF5VzB+oJLuyWrM1QxUSYMFueYX0OCwPuMBHN+QRCuvPeoJCTAjuu8QwOQAS+lgGlJVTDSJHX8KUO4eQboK+NdpQWlm6G0eefZJvfsbM6V8bqHYWtsnLJ7SI8AiGXbmQfWGrXOR2z/6wAiPay8CJm7RXFNTfiTKPVaD4L0R3yJNvy+Use02eI5DwL1pSbmK/kiP4dxOY6GY2N/GZrbLGxgPPBn3G0m8WGbKMGTLnQmxiUG+QZc4+CKPHFtpuaBnRAXuJhkKUfMGa1cSs1x+rRVyZVgO+M5xfiU5qjyQAbczCGASX//flFc/ej6uBU3ikpMsfPQL0dPvlcbqb0cPmxQxeZa4ADvzAjLs+k+R6igz713WMjkcqNZXJOOYhNVpWoEea2ed1jPn3vDf5q1s7b+4589KxqFb7lSk7ZY3Xdwu3GmfS1nn74Uin1R5S/OITN2N5YmgR/e/5Q8j9iwpW4Nnbl/NIdOwfK4Tsencsw=
  on:
    tags: true
    repo: kellyselden/ember-cli-dependency-graph
